shop/myshop/recipe/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'recipe'

urlpatterns = [
    # Post views
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('create/', views.create_recipe, name='create_recipe'),
    path('edit/<int:year>/<int:month>/<int:day>/<slug:post>/', views.edit_recipe, name='edit_recipe'),
    path(
        'tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'
    ),
    path(
        '<int:year>/<int:month>/<int:day>/<slug:post>/',
        views.post_detail,
        name='post_detail'
    ),
    path('rate/<int:post_id>/', views.rate_post, name='rate_post'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path(
        '<int:post_id>/comment/', views.post_comment, name='post_comment'
    ),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),

]

shop/myshop/recipe/templates/recipe/base.html
{% load recipe_tags %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/recipe.css" %}" rel="stylesheet">
</head>
<body>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>

    <div id="sidebar">
        <!-- Recipe Section -->
        <h2>My recipe</h2>
        <p>This is my recipe. I've written {{ total_posts }} posts so far.</p>

        <!-- Create Recipe Button -->
        <p>
            <a href="{% url 'recipe:create_recipe' %}" class="btn btn-primary">Create New Recipe</a>
        </p>

        <p>
            <a href="{% url 'recipe:post_feed' %}">
                Subscribe to my RSS feed
            </a>
        </p>

        <h3>Latest posts</h3>
        {% show_latest_posts 3 %}
        
        <h3>Most commented posts</h3>
        {% get_most_commented_posts as most_commented_posts %}
        <ul>
            {% for post in most_commented_posts %}
                <li>
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>