mysite/blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    # Post views
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path(
        'tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'
    ),
    path(
        '<int:year>/<int:month>/<int:day>/<slug:post>/',
        views.post_detail,
        name='post_detail'
    ),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path(
        '<int:post_id>/comment/', views.post_comment, name='post_comment'
    ),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),


    # Recipe URLs
    # path('recipes/', views.recipe_list, name='recipe_list'),
    # path('recipes/tag/<slug:tag_slug>/', views.recipe_list, name='recipe_list_by_tag'),
    # path('recipes/<int:year>/<int:month>/<int:day>/<slug:recipe>/', views.recipe_detail, name='recipe_detail'),
    # path('recipes/<int:recipe_id>/rate/', views.submit_rating, name='submit_rating'),  # Optional for rating
    # path('recipes/<int:recipe_id>/share/', views.recipe_share, name='recipe_share'),
    # path(
    #     '<int:recipe_id>/comment/', views.recipe_comment, name='recipe_comment'
    # ),
]

mysite/blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/blog.css" %}" rel="stylesheet">
</head>
<body>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>

    <div id="sidebar">
        <!-- Blog Section -->
        <h2>My blog</h2>
        <p>This is my blog. I've written {% total_posts %} posts so far.</p>
        <p>
            <a href="{% url 'blog:post_feed' %}">
                Subscribe to my RSS feed
            </a>
        </p>
        <h3>Latest posts</h3>
        {% show_latest_posts 3 %}
        <h3>Most commented posts</h3>
        {% get_most_commented_posts as most_commented_posts %}
        <ul>
            {% for post in most_commented_posts %}
                <li>
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>